[project]
name = "legal"
version = "0.1.1"
description = "Administrative Scrivener RAG System"
authors = [
    { name = "Admin", email = "admin@example.com" }
]
dependencies = [
    "streamlit>=1.34.0",
    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "langchain-core>=0.1.25",
    "langchain-google-genai>=0.0.9",
    "langchain-google-vertexai>=3.2.1",
    # Added for Vertex AI
    "google-cloud-aiplatform>=1.38.0",
    # Added for Vertex AI
    "langchain-huggingface>=0.0.1",
    "langchain-chroma>=0.1.0",
    "chromadb>=0.4.24",
    "pypdf>=4.0.1",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.10",
    "python-dotenv>=1.0.1",
    "pandas>=2.3.3",
    "openpyxl>=3.1.2",
    "sentence-transformers>=5.2.0",
    "numpy<2.0",
    "streamlit-image-coordinates>=0.4.0",
    "reportlab>=4.4.7",
    "watchdog>=6.0.0",
    "psycopg2-binary>=2.9.11",
    "opencv-python<4.9",
    "opencv-python-headless<4.9",
    "pymupdf>=1.26.7",
    "streamlit-drawable-canvas>=0.9.3",
    "pyperclip>=1.11.0",
    "google-genai>=1.59.0",
    "pyautogui>=0.9.54",
    "python-docx>=1.2.0",
    "streamlit-keyup>=0.3.0",
    "selenium>=4.40.0",
    "webdriver-manager>=4.0.2",
    "pyzipper>=0.3.6",
    "google-auth-oauthlib>=1.2.4",
    "google-api-python-client>=2.188.0",
]
readme = "README.md"
requires-python = ">= 3.10"

[tool.rye]
managed = true
dev-dependencies = []

[tool.rye.scripts]
start = "rye run python src/legal_system/main.py"
pdf = "rye run streamlit run src/legal_system/tools/coord_tool.py"
exp = "rye run python export_code.py"
