"""add status and other columns to file_registry

Revision ID: eaee66a8be74
Revises: 
Create Date: 2026-01-31 21:50:07.957855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaee66a8be74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('kintone_record_id', sa.Integer(), nullable=True))
    op.alter_column('cases', 'sol_case_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='SOL案件No',
               existing_nullable=True)
    op.alter_column('cases', 'introduction_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='紹介日',
               existing_nullable=True)
    op.alter_column('cases', 'referral_sec_branch_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='証券会社支店名',
               existing_nullable=True)
    op.alter_column('cases', 'referral_sec_rep_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='証券会社担当者名',
               existing_nullable=True)
    op.alter_column('cases', 'consent_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='同意書日付',
               existing_nullable=True)
    op.alter_column('deceased', 'hometown',
               existing_type=sa.VARCHAR(),
               comment='本籍地',
               existing_nullable=True)
    op.add_column('file_registry', sa.Column('status', sa.String(), nullable=True))
    op.add_column('file_registry', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('file_registry', sa.Column('extracted_data', sa.Text(), nullable=True))
    op.add_column('heirs', sa.Column('occupation', sa.String(), nullable=True, comment='職業'))
    op.alter_column('heirs', 'hometown',
               existing_type=sa.VARCHAR(),
               comment='本籍地',
               existing_nullable=True)
    op.add_column('real_estate_assets', sa.Column('assessed_value', sa.Float(), nullable=True, comment='固定資産税評価額'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_assets', 'assessed_value')
    op.alter_column('heirs', 'hometown',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='本籍地',
               existing_nullable=True)
    op.drop_column('heirs', 'occupation')
    op.drop_column('file_registry', 'extracted_data')
    op.drop_column('file_registry', 'ai_confidence')
    op.drop_column('file_registry', 'status')
    op.alter_column('deceased', 'hometown',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='本籍地',
               existing_nullable=True)
    op.alter_column('cases', 'consent_date',
               existing_type=sa.DATE(),
               comment='同意書日付',
               existing_nullable=True)
    op.alter_column('cases', 'referral_sec_rep_name',
               existing_type=sa.VARCHAR(),
               comment='証券会社担当者名',
               existing_nullable=True)
    op.alter_column('cases', 'referral_sec_branch_name',
               existing_type=sa.VARCHAR(),
               comment='証券会社支店名',
               existing_nullable=True)
    op.alter_column('cases', 'introduction_date',
               existing_type=sa.DATE(),
               comment='紹介日',
               existing_nullable=True)
    op.alter_column('cases', 'sol_case_number',
               existing_type=sa.VARCHAR(),
               comment='SOL案件No',
               existing_nullable=True)
    op.drop_column('cases', 'kintone_record_id')
    # ### end Alembic commands ###
